#!/bin/sh
#deploy="false"
deploy="true"

image=TruckService
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t mehulmistry348/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push mehulmistry348/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag mehulmistry348/${image}:1.0-SNAPSHOT mehulmistry348/${image}:latest
        docker push mehulmistry348/${image}:latest
    fi
fi