#!/bin/sh
mvn clean package && docker build -t mehulmistry348/TruckService .
docker rm -f TruckService 2>/dev/null || true && docker run -it --name TruckService -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TruckService mehulmistry348/TruckService
