#!/bin/sh
mvn clean package && docker build -t mehulmistry348/TruckSystemFront .
docker rm -f TruckSystemFront 2>/dev/null || true && docker run -it --name TruckSystemFront -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TruckSystemFront mehulmistry348/TruckSystemFront
