#!/bin/sh
mvn clean package && docker build -t mehulmistry348/UserMP .
docker rm -f UserMP 2>/dev/null || true && docker run -it --name UserMP -p 8080:8080 -p 4848:4848 -p 8181:8181 --name UserMP mehulmistry348/UserMP
